on:
  [pull_request]

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: master
    - name: Node setup
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Package
      run: |
        npm ci
        npm test
        npm run package
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git add dist/
        git commit -m "chore: Update dist" || echo "No changes to commit"
        git push origin HEAD:master
